### ISSUE TITLE
Image caching for planet pngs

### ISSUE THREAD

**Issue by aytunch** [Roaa94/flutter-puzzle-hack#2]
Hi @Roaa94 

I watched your presentation on this project and under the performance part you mentioned something about caching the planet images.

Could you kindly explain what it is for and where in the code you did that?

Thank you for this great project.

**Comment by Roaa94** [comment]
Hi Aytunc

I'm very happy that you watched the presentation and glad that you like the project.

Regarding caching images, this is done with a “precacheImage” function built-in in flutter. All you have to do is call this method, I’m calling it in the didChangeDependencies of my App widget, and give it the value of the ImageProvider.


```dart
bool _isInit = true;

@override
void didChangeDependencies() {
  if (_isInit) {
    for (BackgroundLayerType layerType in BackgroundLayers.types) {
      precacheImage(
        Image.asset('assets/images/background/${layerType.name}.png').image,
        context,
      );
    }

    for (int size in Puzzle.supportedPuzzleSizes) {
      precacheImage(
        Image.asset('assets/images/puzzle-solved/solved-${size}x$size.png').image,
        context,
      );
    }
  }
  _isInit = false;
  super.didChangeDependencies();
}
```

You can read more details about this in [this article](https://dashtronaut.app/tutorials/performance) I just published where you can also read about the other performance optimization I mentioned in the presentation: warming up SKSL shaders.

https://dashtronaut.app/tutorials/performance

Feel free to let me know if you have any questions 🙌🏼
