### ISSUE TITLE
riverpod migration

### ISSUE THREAD

**Issue by Shreemanarjun** [Roaa94/flutter-puzzle-hack#9]
I have tried to complete riverpod migration in this repo. Its completed.
Will create PR with previous file structure soon.

(https://github.com/Shreemanarjun/flutter_puzzle_hack_riverpod)

**Comment by Roaa94** [comment]
Hi there, thanks a lot for your efforts and contribution in the previous PRs 🙏🏼
I appreciate your effort to migrate to Riverpod, however I'm doing a major restructure and cleanup of the code (#10) and adding testing while doing the migration, I also would like to not use `ChangeNotifierProvider`.

**Comment by Shreemanarjun** [comment]
Thanks . I think state notifier or New **Notifier** class will be the perfect replacement of change notifier .
